### ISSUE TITLE
a glicth maybe

### ISSUE THREAD

**Issue by FATHULCOOL** [AJS-development/BlobleNoobScriptV3#2]
for some reason wen,t i gonna play bloble.io it (while using this great mod) it said YOU HAVE ANOTHER TAB OPEN. STOP TRYING TO TRICK THE ALGORITHM OR YOU WILL BE BANNED. BUT I DIDN,T HAVE A SECOD PAGE?
ITS JJUST THERE FOR SOME REASON IN MY FIRTS PAGE?

**Comment by Andrews54757** [comment]
Dont open multiple tabs.
