### ISSUE TITLE
ITS SO ANNOYING!1

### ISSUE THREAD

**Issue by FATHULCOOL** [AJS-development/BlobleNoobScriptV3#3]
GOD DAMMIT I WANT IT TO BE FIXED  IT JUST SO ANNOYING U SHOUND TELL HOW TO MAKE ID OR WHAT ID IS I LITERLYY WRITE MY EMAIL AND IT STEAL SAID NOT YOURS GRR

**Comment by Andrews54757** [comment]
No you
