### ISSUE TITLE
SOME PEPLO MANAGE TO ESCAPE UR SYSTEM AND MAANAGE TO BLAME IT TO OTHER PEPLO

### ISSUE THREAD

**Issue by FATHULCOOL** [AJS-development/BlobleNoobScriptV3#5]
I SEE WEN,T I  PLAY CLASSSIC BLOBLE.IO A PLAYER WITH THIS MODS
AND HE ABUSE IT AND USES BOTS!!!
HE THEN SOMEHOW MANAGE TO GIVE ALL THE BLAME TO HIS VICTIM AND IM KINDA ONE OH THE VICTIM

**Comment by Andrews54757** [comment]
They didnt.
